/** Column kinds. `position` is a `(x, y, z)` tuple stored as raw text, or null when absent. */
export type ColumnKind = "text" | "real" | "integer" | "position";

export interface EventColumn {
  /** Property name on parsed rows and on the Drizzle table. */
  key: string;
  /** Database column name, matching the ScrimTime field name in snake_case. */
  column: string;
  kind: ColumnKind;
  /** May be absent at the end of the line in older logs. Stored as null when absent. */
  optional?: true;
  /** May be present but empty; stored as null. */
  nullable?: true;
}

/** Every ScrimTime event type, with its columns in log order (after the event type). */
export const EVENTS = {
  ability_1_used: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
    { key: "playerPosition", column: "player_position", kind: "position", optional: true, nullable: true },
  ],
  ability_2_used: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
    { key: "playerPosition", column: "player_position", kind: "position", optional: true, nullable: true },
  ],
  damage: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "attackerTeam", column: "attacker_team", kind: "text" },
    { key: "attackerName", column: "attacker_name", kind: "text" },
    { key: "attackerHero", column: "attacker_hero", kind: "text" },
    { key: "victimTeam", column: "victim_team", kind: "text" },
    { key: "victimName", column: "victim_name", kind: "text" },
    { key: "victimHero", column: "victim_hero", kind: "text" },
    { key: "eventAbility", column: "event_ability", kind: "text" },
    { key: "eventDamage", column: "event_damage", kind: "real" },
    { key: "isCriticalHit", column: "is_critical_hit", kind: "text" },
    { key: "isEnvironmental", column: "is_environmental", kind: "text" },
    { key: "attackerPosition", column: "attacker_position", kind: "position", optional: true, nullable: true },
    { key: "victimPosition", column: "victim_position", kind: "position", optional: true, nullable: true },
  ],
  defensive_assist: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
  ],
  dva_remech: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "ultimateId", column: "ultimate_id", kind: "integer" },
  ],
  echo_duplicate_end: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "ultimateId", column: "ultimate_id", kind: "integer" },
  ],
  echo_duplicate_start: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
    { key: "ultimateId", column: "ultimate_id", kind: "integer" },
  ],
  healing: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "healerTeam", column: "healer_team", kind: "text" },
    { key: "healerName", column: "healer_name", kind: "text" },
    { key: "healerHero", column: "healer_hero", kind: "text" },
    { key: "healeeTeam", column: "healee_team", kind: "text" },
    { key: "healeeName", column: "healee_name", kind: "text" },
    { key: "healeeHero", column: "healee_hero", kind: "text" },
    { key: "eventAbility", column: "event_ability", kind: "text" },
    { key: "eventHealing", column: "event_healing", kind: "real" },
    { key: "isHealthPack", column: "is_health_pack", kind: "text" },
    { key: "healerPosition", column: "healer_position", kind: "position", optional: true, nullable: true },
    { key: "healeePosition", column: "healee_position", kind: "position", optional: true, nullable: true },
  ],
  hero_spawn: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "previousHero", column: "previous_hero", kind: "integer", nullable: true },
    { key: "heroTimePlayed", column: "hero_time_played", kind: "real" },
  ],
  hero_swap: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "previousHero", column: "previous_hero", kind: "text" },
    { key: "heroTimePlayed", column: "hero_time_played", kind: "real" },
  ],
  kill: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "attackerTeam", column: "attacker_team", kind: "text" },
    { key: "attackerName", column: "attacker_name", kind: "text" },
    { key: "attackerHero", column: "attacker_hero", kind: "text" },
    { key: "victimTeam", column: "victim_team", kind: "text" },
    { key: "victimName", column: "victim_name", kind: "text" },
    { key: "victimHero", column: "victim_hero", kind: "text" },
    { key: "eventAbility", column: "event_ability", kind: "text" },
    { key: "eventDamage", column: "event_damage", kind: "real" },
    { key: "isCriticalHit", column: "is_critical_hit", kind: "text" },
    { key: "isEnvironmental", column: "is_environmental", kind: "text" },
    { key: "assistCount", column: "assist_count", kind: "text", optional: true, nullable: true },
    { key: "attackerPosition", column: "attacker_position", kind: "position", optional: true, nullable: true },
    { key: "victimPosition", column: "victim_position", kind: "position", optional: true, nullable: true },
  ],
  match_end: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "team1Score", column: "team_1_score", kind: "integer" },
    { key: "team2Score", column: "team_2_score", kind: "integer" },
  ],
  match_start: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "mapName", column: "map_name", kind: "text" },
    { key: "mapType", column: "map_type", kind: "text" },
    { key: "team1Name", column: "team_1_name", kind: "text" },
    { key: "team2Name", column: "team_2_name", kind: "text" },
  ],
  mercy_rez: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "resurrecterTeam", column: "resurrecter_team", kind: "text" },
    { key: "resurrecterPlayer", column: "resurrecter_player", kind: "text" },
    { key: "resurrecterHero", column: "resurrecter_hero", kind: "text" },
    { key: "resurrecteeTeam", column: "resurrectee_team", kind: "text" },
    { key: "resurrecteePlayer", column: "resurrectee_player", kind: "text" },
    { key: "resurrecteeHero", column: "resurrectee_hero", kind: "text" },
  ],
  objective_captured: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "capturingTeam", column: "capturing_team", kind: "text" },
    { key: "objectiveIndex", column: "objective_index", kind: "integer" },
    { key: "controlTeam1Progress", column: "control_team_1_progress", kind: "real" },
    { key: "controlTeam2Progress", column: "control_team_2_progress", kind: "real" },
    { key: "matchTimeRemaining", column: "match_time_remaining", kind: "real" },
  ],
  objective_updated: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "previousObjectiveIndex", column: "previous_objective_index", kind: "integer" },
    { key: "currentObjectiveIndex", column: "current_objective_index", kind: "integer" },
  ],
  offensive_assist: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
  ],
  payload_progress: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "capturingTeam", column: "capturing_team", kind: "text" },
    { key: "objectiveIndex", column: "objective_index", kind: "integer" },
    { key: "payloadCaptureProgress", column: "payload_capture_progress", kind: "real" },
  ],
  player_stat: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "eliminations", column: "eliminations", kind: "integer" },
    { key: "finalBlows", column: "final_blows", kind: "integer" },
    { key: "deaths", column: "deaths", kind: "integer" },
    { key: "allDamageDealt", column: "all_damage_dealt", kind: "real" },
    { key: "barrierDamageDealt", column: "barrier_damage_dealt", kind: "real" },
    { key: "heroDamageDealt", column: "hero_damage_dealt", kind: "real" },
    { key: "healingDealt", column: "healing_dealt", kind: "real" },
    { key: "healingReceived", column: "healing_received", kind: "real" },
    { key: "selfHealing", column: "self_healing", kind: "real" },
    { key: "damageTaken", column: "damage_taken", kind: "real" },
    { key: "damageBlocked", column: "damage_blocked", kind: "real" },
    { key: "defensiveAssists", column: "defensive_assists", kind: "integer" },
    { key: "offensiveAssists", column: "offensive_assists", kind: "integer" },
    { key: "ultimatesEarned", column: "ultimates_earned", kind: "integer" },
    { key: "ultimatesUsed", column: "ultimates_used", kind: "integer" },
    { key: "multikillBest", column: "multikill_best", kind: "integer" },
    { key: "multikills", column: "multikills", kind: "integer" },
    { key: "soloKills", column: "solo_kills", kind: "integer" },
    { key: "objectiveKills", column: "objective_kills", kind: "integer" },
    { key: "environmentalKills", column: "environmental_kills", kind: "integer" },
    { key: "environmentalDeaths", column: "environmental_deaths", kind: "integer" },
    { key: "criticalHits", column: "critical_hits", kind: "integer" },
    { key: "criticalHitAccuracy", column: "critical_hit_accuracy", kind: "real" },
    { key: "scopedAccuracy", column: "scoped_accuracy", kind: "real" },
    { key: "scopedCriticalHitAccuracy", column: "scoped_critical_hit_accuracy", kind: "real" },
    { key: "scopedCriticalHitKills", column: "scoped_critical_hit_kills", kind: "integer" },
    { key: "shotsFired", column: "shots_fired", kind: "integer" },
    { key: "shotsHit", column: "shots_hit", kind: "integer" },
    { key: "shotsMissed", column: "shots_missed", kind: "integer" },
    { key: "scopedShotsFired", column: "scoped_shots_fired", kind: "integer" },
    { key: "scopedShotsHit", column: "scoped_shots_hit", kind: "integer" },
    { key: "weaponAccuracy", column: "weapon_accuracy", kind: "real" },
    { key: "heroTimePlayed", column: "hero_time_played", kind: "real" },
  ],
  point_progress: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "capturingTeam", column: "capturing_team", kind: "text" },
    { key: "objectiveIndex", column: "objective_index", kind: "integer" },
    { key: "pointCaptureProgress", column: "point_capture_progress", kind: "real" },
  ],
  remech_charged: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
    { key: "ultimateId", column: "ultimate_id", kind: "integer" },
  ],
  round_end: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "capturingTeam", column: "capturing_team", kind: "text" },
    { key: "team1Score", column: "team_1_score", kind: "integer" },
    { key: "team2Score", column: "team_2_score", kind: "integer" },
    { key: "objectiveIndex", column: "objective_index", kind: "integer" },
    { key: "controlTeam1Progress", column: "control_team_1_progress", kind: "real" },
    { key: "controlTeam2Progress", column: "control_team_2_progress", kind: "real" },
    { key: "matchTimeRemaining", column: "match_time_remaining", kind: "real" },
  ],
  round_start: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "capturingTeam", column: "capturing_team", kind: "text" },
    { key: "team1Score", column: "team_1_score", kind: "integer" },
    { key: "team2Score", column: "team_2_score", kind: "integer" },
    { key: "objectiveIndex", column: "objective_index", kind: "integer" },
  ],
  setup_complete: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "roundNumber", column: "round_number", kind: "integer" },
    { key: "matchTimeRemaining", column: "match_time_remaining", kind: "real" },
  ],
  ultimate_charged: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
    { key: "ultimateId", column: "ultimate_id", kind: "integer" },
  ],
  ultimate_end: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text", nullable: true },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
    { key: "ultimateId", column: "ultimate_id", kind: "integer" },
    { key: "playerPosition", column: "player_position", kind: "position", optional: true, nullable: true },
  ],
  ultimate_start: [
    { key: "matchTime", column: "match_time", kind: "real" },
    { key: "playerTeam", column: "player_team", kind: "text" },
    { key: "playerName", column: "player_name", kind: "text" },
    { key: "playerHero", column: "player_hero", kind: "text" },
    { key: "heroDuplicated", column: "hero_duplicated", kind: "text" },
    { key: "ultimateId", column: "ultimate_id", kind: "integer" },
    { key: "playerPosition", column: "player_position", kind: "position", optional: true, nullable: true },
  ],
} as const satisfies Record<string, readonly EventColumn[]>;

export type EventType = keyof typeof EVENTS;

export const EVENT_TYPES = Object.keys(EVENTS) as EventType[];

/** A parsed event row: column key to coerced value. */
export type EventRow = Record<string, string | number | null>;
